### ISSUE TITLE
NullPointerException when source certificate has no extensions

### ISSUE THREAD

**Issue by seven1oe** [sensepost/apostille#3]
It will throw a NullPointerException when source certificate has no extensions.
```
Exception in thread "main" java.lang.NullPointerException
        at net.za.dawes.apostille.Apostille.getExtensions(Apostille.java:313)
        at net.za.dawes.apostille.Apostille.copyAndSign(Apostille.java:252)
        at net.za.dawes.apostille.Apostille.cloneCertificates(Apostille.java:200)
        at net.za.dawes.apostille.Apostille.cloneCertificates(Apostille.java:151)
        at net.za.dawes.apostille.Main.main(Main.java:152)
```
Checking null in Apostille.java line 313 works for me:
```
if (criticalExtensionOids == null){
    return extensions;
}
```

**Comment by RoganDawes** [comment]
Good catch! I'll add a check. Thanks for the report.
